### ISSUE TITLE
Can you explain better README?

### ISSUE THREAD

**Issue by ghost** [MaurizioSodano/AirportXplaneParser#3]
Hi Maurizio,
Can you explain better what this project does (use case, scenario..)?
Then you should separate the core logic part from the GUI, and maybe use Java Swing (not awt).
See this link: https://www.guru99.com/java-swing-gui.html
As advice, the best would be a nice simple GUI using Angular in electron (as a desktop app, you can call the jar api in the main node electron process IPC).
Thanks

**Comment by MaurizioSodano** [comment]
Hi Angelo, thanks for your feedback. I'll try to improve the README.
Regarding the GUI I'll make an effort to use Swing instead of awt. 
Anyway the GUI is not the focus of this repository. It is just a quick and dirty example to show the results on a map. The main purpose is more a library used to parse airport maps from XPlane.
Unfortunately Angular is not yet in my toolbox. But I'm going to add. In the meantime any pull request are very welcome

**Comment by MaurizioSodano** [comment]
Hi @amanganiello90 , I've separated the logic with the GUI
I've also added an assembly module to make it more usable

**Comment by ghost** [comment]
Good!
